

--insert tipo
INSERT INTO "TIPO"("NOMBRE", "CAPACIDAD") VALUES ('Economico',45 );
INSERT INTO "TIPO"("NOMBRE", "CAPACIDAD") VALUES ('Epresarial',35 );

--INSERT BUS
INSERT INTO "BUS"("MATRICULA", "MARCA", "TIPO")VALUES ('MMQ1', 'TOYOTA', 1);
INSERT INTO "BUS"("MATRICULA", "MARCA", "TIPO")VALUES ('MMQ2', 'TOYOTA', 1);
INSERT INTO "BUS"("MATRICULA", "MARCA", "TIPO")VALUES ('MMQ3', 'TOYOTA', 1);
INSERT INTO "BUS"("MATRICULA", "MARCA", "TIPO")VALUES ('MMQ4', 'TOYOTA', 1);
INSERT INTO "BUS"("MATRICULA", "MARCA", "TIPO")VALUES ('MMQ5', 'TOYOTA', 1);
INSERT INTO "BUS"("MATRICULA", "MARCA", "TIPO")VALUES ('MMQ6', 'TOYOTA', 1);
INSERT INTO "BUS"("MATRICULA", "MARCA", "TIPO")VALUES ('MMQ7', 'TOYOTA', 1);
INSERT INTO "BUS"("MATRICULA", "MARCA", "TIPO")VALUES ('MMQ8', 'TOYOTA', 1);
INSERT INTO "BUS"("MATRICULA", "MARCA", "TIPO")VALUES ('MMF9', 'MAZDA', 2);
INSERT INTO "BUS"("MATRICULA", "MARCA", "TIPO")VALUES ('MMF10', 'MAZDA', 2);

--PUNTO
INSERT INTO "PUNTO"("DIRECCION") VALUES ('12 AV PARQUE 1 ZONA 2 CHIMALTENANGO');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('13 AV LOS ALAMOS 2 ZONA 5 GUATEMALA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('14 AV PARQUE 4 ZONA 6 CHIMALTENANGO');

INSERT INTO "PUNTO"("DIRECCION") VALUES ('3 AV TEATRO ZONA 4 ESCUINTLA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('4 AV ZONA 3 ESCUINTLA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('2 AV ZONA 5 GUATEMALA');

INSERT INTO "PUNTO"("DIRECCION") VALUES ('5 AV PARQUE 3 ZONA 3 ZACAPA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('2 AV MERCADO ZONA 2 GUATEMALA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('6 AV PARQUE 6 ZONA 2 ZACAPA');

INSERT INTO "PUNTO"("DIRECCION") VALUES ('ZONA 10 GUATEMALA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('ZONA 8 IZABAL');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('ZONA 6 IZABAL');

INSERT INTO "PUNTO"("DIRECCION") VALUES ('12 AV PARQUE 1 ZONA 2 GUATEMALA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('13 AV LOS ALAMOS 2 ZONA 5 HUEHUETENAGO');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('14 AV PARQUE 4 ZONA 6 HUEHUETENAGO');

INSERT INTO "PUNTO"("DIRECCION") VALUES ('3 AV TEATRO ZONA 4 SOLOLA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('4 AV ZONA 3 GUATEMALA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('2 AV ZONA 5 SOLALA');

INSERT INTO "PUNTO"("DIRECCION") VALUES ('5 AV PARQUE 3 ZONA 3 JALAPA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('2 AV MERCADO ZONA 8 GUATEMALA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('6 AV PARQUE 6 ZONA 2 GUATEMALA');

INSERT INTO "PUNTO"("DIRECCION") VALUES ('ZONA 10 GUATEMALA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('ZONA 8 TOTONICAPAN');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('ZONA 6 TOTONICAPAN');


INSERT INTO "PUNTO"("DIRECCION") VALUES ('5 AV PARQUE 3 ZONA 3 ALTA VERAPAZ');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('2 AV MERCADO ZONA 8 ALTA VERAPAZ');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('6 AV PARQUE 6 ZONA 2 GUATEMALA');

INSERT INTO "PUNTO"("DIRECCION") VALUES ('ZONA 10 GUATEMALA');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('ZONA 8 BAJA VERAPAZ');
INSERT INTO "PUNTO"("DIRECCION") VALUES ('ZONA 6 BAJA VERAPAZ');

--RUTA
INSERT INTO "RUTA"("NOMBRE", "ORIGEN", "DESTINO")VALUES ('RUTA1', 'GUATEMALA', 'CHIMALTENANGO');
INSERT INTO "RUTA"("NOMBRE", "ORIGEN", "DESTINO")VALUES ('RUTA2', 'GUATEMALA', 'ESCUINTLA');
INSERT INTO "RUTA"("NOMBRE", "ORIGEN", "DESTINO")VALUES ('RUTA3', 'GUATEMALA', 'ZACAPA');
INSERT INTO "RUTA"("NOMBRE", "ORIGEN", "DESTINO")VALUES ('RUTA4', 'GUATEMALA', 'IZABAL');
INSERT INTO "RUTA"("NOMBRE", "ORIGEN", "DESTINO")VALUES ('RUTA5', 'GUATEMALA', 'HUEHUETENAGO');
INSERT INTO "RUTA"("NOMBRE", "ORIGEN", "DESTINO")VALUES ('RUTA6', 'GUATEMALA', 'SOLOLA');
INSERT INTO "RUTA"("NOMBRE", "ORIGEN", "DESTINO")VALUES ('RUTA7', 'GUATEMALA', 'JALAPA');
INSERT INTO "RUTA"("NOMBRE", "ORIGEN", "DESTINO")VALUES ('RUTA8', 'GUATEMALA', 'TOTONICAPAN');
INSERT INTO "RUTA"("NOMBRE", "ORIGEN", "DESTINO")VALUES ('RUTA9', 'GUATEMALA', 'ALTA VERAPAZ');
INSERT INTO "RUTA"("NOMBRE", "ORIGEN", "DESTINO")VALUES ('RUTA10', 'GUATEMALA', 'BAJA VERAPAZ');

--VIAJE (SOLO 6)
INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (100, 10.00, '8:00', '10:00', 1, 2, 1);
INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (40, 5.00, '10:00', '10:30', 1, 1, 3);

INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (80, 19.00, '8:00', '10:00', 2, 6, 5);
INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (50, 10.00, '10:00', '10:30', 2, 5, 4);

INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (140, 8.00, '8:00', '10:00', 3, 8,9);
INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (90, 10.00, '10:00', '10:30', 3, 9, 7);

INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (70, 15.00, '8:00', '10:00', 4, 10,11);
INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (40, 5.00, '10:00', '10:30', 4, 11, 12);

INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (70, 15.00, '8:00', '10:00', 5, 13,14);
INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (40, 5.00, '10:00', '10:30', 5, 14, 15);

INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (90, 20.00, '8:00', '10:00', 6, 17,18);
INSERT INTO "VIAJE"("KILOMETROS", "PRECIO", "H_SALIDA", "H_LLEGADA", "RUTA", "P_INICIO", "P_LLEGADA")
VALUES (30, 4.00, '10:00', '10:30', 6, 18, 16);

--INTINERARIO
INSERT INTO "INTINERARIO"("FECHA", "H_SALIDA", "H_LLEGADA", "BUS", "RUTA")
    VALUES ('25/04/2015', '8:00', '12:00', 1, 1);

INSERT INTO "INTINERARIO"("FECHA", "H_SALIDA", "H_LLEGADA", "BUS", "RUTA")
    VALUES ('25/04/2015', '10:00', '15:00', 2, 2);

INSERT INTO "INTINERARIO"("FECHA", "H_SALIDA", "H_LLEGADA", "BUS", "RUTA")
    VALUES ('25/04/2015', '11:00', '16:00', 3, 3);

INSERT INTO "INTINERARIO"("FECHA", "H_SALIDA", "H_LLEGADA", "BUS", "RUTA")
    VALUES ('25/04/2015', '12:00', '17:00', 4, 4);

INSERT INTO "INTINERARIO"("FECHA", "H_SALIDA", "H_LLEGADA", "BUS", "RUTA")
    VALUES ('26/04/2015', '12:00', '17:00', 5, 1);

INSERT INTO "INTINERARIO"("FECHA", "H_SALIDA", "H_LLEGADA", "BUS", "RUTA")
    VALUES ('26/04/2015', '12:00', '17:00', 7, 3);

INSERT INTO "INTINERARIO"("FECHA", "H_SALIDA", "H_LLEGADA", "BUS", "RUTA")
    VALUES ('26/04/2015', '12:00', '17:00', 8, 2);